FROM php:7.4.9-apache-buster
ENV DEBIAN_FRONTEND noninteractive
ENV APACHE_DOCUMENT_ROOT /var/www/html/public


ENV APACHE_USER=www-data
ENV APACHE_GROUP=www-data

# Add a non-root user:
ARG PUID=1000
ENV PUID ${PUID}
ARG PGID=1000
ENV PGID ${PGID}

WORKDIR /var/www/html
RUN apt-get update && \
    apt-get -yq dist-upgrade && \
    apt-get -yq install libfreetype6-dev libpng-dev libjpeg-dev libicu-dev libmcrypt-dev libgd-dev libzip-dev git zip unzip && \
    curl -sS https://getcomposer.org/installer | php  && \
    mv -v composer.phar /usr/local/bin/composer && \
    mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini && \
    docker-php-ext-configure zip && \
    docker-php-ext-install -j$(nproc) exif gd intl opcache mysqli zip pdo pdo_mysql && \
    # composer create-project bolt/project . && \
    # bin/console doctrine:database:create && \
    # bin/console doctrine:schema:create && \
    # bin/console bolt:add-user --admin admin secret email@example.com Admin && \
    apt-get -y --purge remove libfreetype6-dev libpng-dev libjpeg-dev libicu-dev libmcrypt-dev libgd-dev libzip-dev && \
    sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf && \
    a2enmod rewrite && \
    # chown -R www-data.www-data . && \
    # Change apache user's (www-data) PUID & PGID
    # Check: https://askubuntu.com/questions/645236/command-to-list-all-users-with-their-uid
    # https://github.com/kconde2/docker-apache-php-laravel/blob/master/Dockerfile
    usermod -u ${PUID} ${APACHE_USER} && groupmod -g ${PGID} ${APACHE_GROUP} && \
    apt-get clean && \
    rm -rf /var/lib/{apt,dpkg,cache,log}
EXPOSE 80
